### ISSUE TITLE
Chrome driver only supports Chrome version 87

### ISSUE THREAD

**Issue by theaddies** [Hari-Nagarajan/fairgame#565] opened 2021-03-15 22:09 UTC
I have 2 separate instances of fairgame both running the dev branch.  Both worked fine for quite a while.  Just yesterday I started to get the error below on one of them.  I believe the program somehow thinks I still have a Chrome window open, but I do not.  I have rebooted and still receive the error.  Is there some file remant I can delete in the fairgame folder to reset things back to normal.

2021-03-15 18:03:41|0.6.0.dev5|WARNING|FairGame PRE-RELEASE v0.6.0.dev5
2021-03-15 18:03:41|0.6.0.dev5|INFO|Initializing Global configuration...
2021-03-15 18:03:41|0.6.0.dev5|INFO|No Apprise config found at config/apprise.conf.
2021-03-15 18:03:41|0.6.0.dev5|INFO|For notifications, see config/apprise.conf_template
2021-03-15 18:03:41|0.6.0.dev5|INFO|Initializing Amazon configuration...
2021-03-15 18:03:41|0.6.0.dev5|INFO|Reading credentials from: config/amazon_credentials.json
Credential file password: *******************
2021-03-15 18:03:53|0.6.0.dev5|ERROR|Message: session not created: This version of ChromeDriver only supports Chrome version 87
Current browser version is 89.0.4389.82 with binary path C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

2021-03-15 18:03:53|0.6.0.dev5|ERROR|If you have a JSON warning above, try cleaning your profile (e.g. --clean-profile)
2021-03-15 18:03:53|0.6.0.dev5|ERROR|If that's not it, you probably have a previous Chrome window open. You should close it.

**Comment by SirDystic** [comment] 2021-03-17 14:42
Dupe of #549

**Comment by timbru31** [comment] 2021-04-20 16:31
@DakkJaniels you should be good to close the issue here

**Closed** 2021-04-20 16:35 UTC
