### ISSUE TITLE
Add newegg? 

### ISSUE THREAD

**Issue by SagittariusC** [Hari-Nagarajan/fairgame#113] opened 2020-09-24 00:30 UTC
Maybe just stock checking with an alarm at first, that alone would be useful. Not sure if it can get as far as auto checkout.

**Comment by DiehardFiero** [comment] 2020-09-24 01:39
Yes please! Newegg should definitely be next if possible!

**Comment by MahindraPersaud** [comment] 2020-09-24 03:02
There is a way to have newegg auto add to cart using this url https://secure.newegg.com/Shopping/AddtoCart.aspx?Submit=ADD&ItemList=N82E16814487526 for the 3090 ftw3 ultra. there are a lot of other urls for other cards too.

**Comment by Hari-Nagarajan** [comment] 2020-09-24 03:17
I've assigned this as a task to myself

**Comment by MahindraPersaud** [comment] 2020-09-24 03:21
@Hari-Nagarajan There is another open-source store scanner out there called Nvidia-snatcher, which has the direct URL for a lot of the various GPUS and a couple of other stores. I'm attempting to currently add the Newegg as well but my python with chromium isn't that great.

**Comment by Hari-Nagarajan** [comment] 2020-09-24 03:22
Yeah we share info with the snatcher devs as well

**Comment by MahindraPersaud** [comment] 2020-09-24 03:27
Some quick things I've found.

The newegg login page's url is (https://secure.newegg.com/NewMyAccount/AccountLogin.aspx)
The Sign In button doesn't have an ID or so, it'll be tricky to get going unless you can think of an alternative.

ID of password input is `labeled-input-password`

Head of the home page is "Computer Components, Computer Parts, LCD Monitors, Video Cards, Processors and CPUs, Computer Memory, RAM, Digital Cameras, Printers, Notebook Computers, Laptops, Motherboards, Flash Memory, PC Speakers, LED TV, Unlocked Phones, Office Supplies, Home Appliances"

Head of sign in is "Newegg - Sign In"

**Closed** 2020-12-10 22:44 UTC
Labels: enhancement

**Comment by shambik** [comment] 2020-12-13 17:15
I wrote one that notifies when item is in stock
Maybe it can help until autocheckout will be added 

https://github.com/shambik/NeweggScraper

**Comment by qwook** [comment] 2020-12-15 00:57
I'm very curious, why are these PR's being closed before the issue is resolved?

**Comment by DakkJaniels** [comment] 2020-12-15 01:06
This is an issue, not a PR. And it's not an "issue", it's an ask, and at this point it's not happening. I'd like to keep the issues log to actual issues with the current code base.

**Comment by qwook** [comment] 2020-12-15 01:09
Sorry I meant "issues." And I see, I am used to Github Issues being used as a tracking tool for ideas, tasks, feedback and bugs and not only "Issues."

**Comment by DakkJaniels** [comment] 2020-12-15 01:24
I'm not sure what the point is of keeping "add newegg" on the issues log if it's not going to happen. Obviously all those things you listed are covered under issues. And if something like "add Newegg" was actually relevant and achievable with who is volunteering to write code for this, then I would keep it on the log as something to track. But at this point, that is not the case, so I don't see the point in clogging up the log with things that are not currently (now and in the future) relevant. If/when that changes, the issue can be reopened.

**Comment by qwook** [comment] 2020-12-15 02:15
I'll drop any info here since there isn't any other place to.

Newegg has some antibot measures so autocheckout may not be viable but you can still run some AJAX calls while the selenium page is open which spamming add to cart. This is much more lightweight than the aspx add to cart calls I've been seeing.

Add2Cart api:
```
POST https://www.newegg.com/api/Add2Cart

{"ItemList":[{"ItemGroup":"Combo","ItemNumber":"4211902","Quantity":1,"OptionalInfos":null,"SaleType":"Sales"}],"CustomerNumber":"<CUSTOMER ID>"}
```

Customer ID is obtainable through:
```
parseCookie = str =>
  str
    .split(';')
    .map(v => v.split('='))
    .reduce((acc, v) => {
      acc[decodeURIComponent(v[0].trim())] = decodeURIComponent(v[1].trim());
      return acc;
    }, {});
let cookie = parseCookie(document.cookie)
customer_info = JSON.parse(cookie.NV_OTHERINFO.substr(2))
customer_id = decodeURIComponent(customer_info.Sites.USA.Values.sc)
console.log(customer_id)
```
 Expected response
```{"BuyAlongItemInfos":[],"Result":"Success","MessageEntitys":null}```
