### ISSUE TITLE
Add Newegg support

### ISSUE THREAD

**Issue by zero-radiance** [Hari-Nagarajan/fairgame#456] opened 2020-12-31 01:30 UTC
Newegg appears to have a lot more stock (small daily drops) than Amazon (nothing).

This could work in a very simple manner. Below is how I managed to buy something from Newegg acting like a bot myself.

1. Create a Wishlist with items you care about.
2. Keep refreshing the page with the Wishlist until the "ADD ALL TO CART" button becomes active.
3. Click the button, it takes you straight to the Cart page.
4. Click the "SECURE CHECKOUT" button.
5. The next page asks for "CVV2" (the only available field). Once that is filled, click the "PLACE ORDER" button.

As you can see from the description, it can be easily automated. Doing this manually between 5-8 pm is the only way to beat the bots right now (cards are in stock for less than 10 seconds, so you have to spam F5 continuously).

**Comment by DakkJaniels** [comment] 2020-12-31 02:09
At this point, not going to happen unless you are going to make the PR to do it. Also, this is a duplicate of previously closed issued. Someone is working on a difference repo in our discord that is for newegg, if you are looking for a newegg bot.

**Closed by DakkJaniels** 2020-12-31 02:09 UTC
