### ISSUE TITLE
Amazon now redirects to https://smile.amazon.com/dp/*/ref=olp_dp_redir

### ISSUE THREAD

**Issue by nickreilly** [Hari-Nagarajan/fairgame#474] opened 2021-01-26 11:44 UTC
**Describe the bug**
Amazon now either redirecting to a site that is non-functional for the bot, or is now soft banning smile links.  

**To Reproduce**

Just running the bot!  It typically would go to the available from these sellers page, and it no longer does this.  

**Screenshots**
![gnome-shell-screenshot-PVX9W0](https://user-images.githubusercontent.com/19576133/105840371-f123e680-5fa0-11eb-9779-193eb0548395.png)

**Desktop (please complete the following information):**
 - OS: Pop!_Os 20.10 (Ubuntu)
 - Browser- Chrome  88.0.4324.96
 - Version v0.5.4

**Additional context**
Log is attached [fairgame.log.3.txt](https://github.com/Hari-Nagarajan/fairgame/files/5873056/fairgame.log.3.txt)

**Comment by onassif** [comment] 2021-01-26 12:17
Same Issue Here!
OS: Ubuntu 20.04.1
Browser- Chrome 88.0.4324.96
Version v0.5.4

**Comment by interbiznw** [comment] 2021-01-26 12:26
Same issue here
Windows 10
Chrome 87.0.4280.141
Version 0.6.0.dev1

```?[32m2021-01-26 04:22:44?[0m|0.6.0.dev1|?[1;30mINFO?[0m|Waiting for home page.
?[32m2021-01-26 04:22:46?[0m|0.6.0.dev1|?[1;30mINFO?[0m|Already logged in
?[32m2021-01-26 04:22:47?[0m|0.6.0.dev1|?[1;30mINFO?[0m|Checking stock for items.
?[32m2021-01-26 04:22:49?[0m|0.6.0.dev1|?[1;30mINFO?[0m|Attempting to click the open offers link...
Traceback (most recent call last):
  File "app.py", line 5, in <module>
    cli.main()
  File "C:\Users\Administrator\.virtualenvs\FAIRGAME_1-T8yO2X2e\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Administrator\.virtualenvs\FAIRGAME_1-T8yO2X2e\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\Users\Administrator\.virtualenvs\FAIRGAME_1-T8yO2X2e\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Administrator\.virtualenvs\FAIRGAME_1-T8yO2X2e\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Administrator\.virtualenvs\FAIRGAME_1-T8yO2X2e\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\Administrator\Downloads\FAIRGAME 1\cli\cli.py", line 38, in decorator
    func(*args, **kwargs)
  File "C:\Users\Administrator\Downloads\FAIRGAME 1\cli\cli.py", line 185, in amazon
    amzn_obj.run(delay=delay, test=test)
  File "C:\Users\Administrator\Downloads\FAIRGAME 1\stores\amazon.py", line 208, in run
    asin = self.run_asins(delay)
  File "C:\Users\Administrator\Downloads\FAIRGAME 1\utils\debugger.py", line 15, in wrapper_debug
    value = func(*args, **kwargs)
  File "C:\Users\Administrator\Downloads\FAIRGAME 1\stores\amazon.py", line 414, in run_asins
    if self.check_stock(asin, self.reserve_min[i], self.reserve_max[i]):
  File "C:\Users\Administrator\Downloads\FAIRGAME 1\utils\debugger.py", line 15, in wrapper_debug
    value = func(*args, **kwargs)
  File "C:\Users\Administrator\Downloads\FAIRGAME 1\stores\amazon.py", line 519, in check_stock
    self.driver.find_element_by_xpath(
  File "C:\Users\Administrator\.virtualenvs\FAIRGAME_1-T8yO2X2e\lib\site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\Administrator\.virtualenvs\FAIRGAME_1-T8yO2X2e\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\Administrator\.virtualenvs\FAIRGAME_1-T8yO2X2e\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Administrator\.virtualenvs\FAIRGAME_1-T8yO2X2e\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_respo
nse
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable
  (Session info: chrome=87.0.4280.141)

?[32m2021-01-26 04:22:49?[0m|0.6.0.dev1|?[1;30mINFO?[0m|Cleaning up after web driver...```

**Comment by interbiznw** [comment] 2021-01-26 12:28
also got this another time

```File "C:\Users\Administrator\.virtualenvs\FAIRGAME_1-T8yO2X2e\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_respo
nse
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <a id="buybox-see-all-buying-choices-announce
" href="/gp/offer-listing/B08R876RTH/ref=dp_olp_unknown_mbc" title="See All Buying Options" class="a-button-text" role="button">...</a> is not clickab
le at point (1109, 288). Other element would receive the click: <div class="a-fixed-right-grid-inner" style="padding-right:150px">...</div>
  (Session info: chrome=87.0.4280.141)

?[32m2021-01-26 04:15:01?[0m|0.6.0.dev1|?[1;30mINFO?[0m|Cleaning up after web driver...```

**Comment by WUZUP1998** [comment] 2021-01-26 12:28
Same here.  Looks like the trouble started about 2 hours ago.

![image](https://user-images.githubusercontent.com/20755600/105844974-0ea87e80-5fa8-11eb-8dea-77575808c6ac.png)

**Comment by interbiznw** [comment] 2021-01-26 12:37
yep seems they changed the url even if you open amazon in your normal browser
```https://www.amazon.com/gp/offer-listing/*/ref=dp_olp_NEW_mbc?ie=UTF8&condition=NEW```

**Comment by gregoiredelzongle** [comment] 2021-01-26 13:30
Duplicate of #460 
See #467 for a hotfix

**Comment by interbiznw** [comment] 2021-01-26 13:35
> Duplicate of #460
> See #467 for a hotfix

Already using that branch, and getting errors now...So that in itself is no longer a fix since they must have changed something again

**Comment by v-jacob** [comment] 2021-01-26 13:39
Same issue here

**Comment by nickreilly** [comment] 2021-01-26 13:46
I just pulled the dev branch, and no success.  Here is the traceback 

```
Traceback (most recent call last):
  File "app.py", line 5, in <module>
    cli.main()
  File "/home/nick/.local/share/virtualenvs/fairgame-R3R5UNSk/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/nick/.local/share/virtualenvs/fairgame-R3R5UNSk/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/nick/.local/share/virtualenvs/fairgame-R3R5UNSk/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/nick/.local/share/virtualenvs/fairgame-R3R5UNSk/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/nick/.local/share/virtualenvs/fairgame-R3R5UNSk/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/nick/Applications/fairgame/cli/cli.py", line 38, in decorator
    func(*args, **kwargs)
  File "/home/nick/Applications/fairgame/cli/cli.py", line 185, in amazon
    amzn_obj.run(delay=delay, test=test)
  File "/home/nick/Applications/fairgame/stores/amazon.py", line 208, in run
    asin = self.run_asins(delay)
  File "/home/nick/Applications/fairgame/utils/debugger.py", line 15, in wrapper_debug
    value = func(*args, **kwargs)
  File "/home/nick/Applications/fairgame/stores/amazon.py", line 414, in run_asins
    if self.check_stock(asin, self.reserve_min[i], self.reserve_max[i]):
  File "/home/nick/Applications/fairgame/utils/debugger.py", line 15, in wrapper_debug
    value = func(*args, **kwargs)
  File "/home/nick/Applications/fairgame/stores/amazon.py", line 519, in check_stock
    self.driver.find_element_by_xpath(
  File "/home/nick/.local/share/virtualenvs/fairgame-R3R5UNSk/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/home/nick/.local/share/virtualenvs/fairgame-R3R5UNSk/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/home/nick/.local/share/virtualenvs/fairgame-R3R5UNSk/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/nick/.local/share/virtualenvs/fairgame-R3R5UNSk/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <a id="buybox-see-all-buying-choices-announce" href="/gp/offer-listing/B08HR6FMF3/ref=dp_olp_unknown_mbc" title="See All Buying Options" class="a-button-text" role="button">...</a> is not clickable at point (1117, 288). Other element would receive the click: <form method="post" action="/gp/add-to-cart/html/ref=aod_dpdsk_used_1" class="aod-atc-form-header-desktop a-spacing-none">...</form>
  (Session info: chrome=88.0.4324.96)
```

**Comment by unapproachable** [comment] 2021-01-26 13:51
Sadly, I still see the offers page on my bot.  I'll try some things to see if I can see it, but my local version is currently working.  The cover exception is typically because something is literally covering up the button or link it's trying to click.  Are the windows maximized?  Can you find the element that's covered and see why it's covered?  Is it obvious what's not being clicked?

**Comment by nickreilly** [comment] 2021-01-26 13:55
I appreciate all your help!  I tried resizing the window and didn't notice any change.  I had not noticed anything covering up the buttons- it seemed that it failed on pages that were totally unavailable and no scalped items available if that helps, so there was no "see buying options" or "these sellers" links for the bot to click on.  Maybe the covering up was just the cached site not displaying that at all.

Another user in the discord suggested to remove the .profile-amz folder, and that is currently working.  They also suggested that it is a temporary fix.

**Comment by DakkJaniels** [comment] 2021-01-26 14:28
If anyone posting here has this error, can you please provide as much info as you can on how you are running the bot, including but not limited to the contents of your amazon_config.json file, any options you are running the bot with (e.g., `--checkshipping`), if you are running multiple instances, etc.

I'm not seeing the offers page redirect personally, so it would be helpful in figuring out why this is occurring.

In the meantime, as suggested above, try deleting your .profile-amz folder from the FairGame folder and see if that fixes the issue for you.

**Comment by dexmar** [comment] 2021-01-26 15:55
I started getting this message last night around 10pm pacific. I deleted  .profile-amz folder and it appeared to return to normal function. Around 2:47am the redirect started up again, but this time with the fly-open menu listing other sellers. Tried deleting the  .profile-amz folder but that did not cure the problem. So I stopped the bot for a while, deleted the  .profile-amz folder, and then restarted the bot and it is functioning again, we'll see how long...

**Comment by thecosmicpeach** [comment] 2021-01-26 16:09
Deleting the .profile-amz folder solved the issue for me as well. Everything appears to be running optimally again.

**Comment by BigClur** [comment] 2021-01-26 16:22
same, deleted the .profile-amz folder fixed it for now.

**Comment by megalomenyak** [comment] 2021-01-26 16:28
Same, deleted the folder but didnt work for Amazon.de.

**Comment by bobbintb** [comment] 2021-01-26 17:01
I deleted the folder but it didn't work for me.

**Comment by megalomenyak** [comment] 2021-01-26 17:05
@bobbintb me neither but after that installed fairgame again. And working good now. Same thing deleting the folder.

**Comment by onassif** [comment] 2021-01-26 17:05
> I deleted the folder but it didn't work for me.

Try this: as soon as the chrome window appears, maximize it. I tried that and not sure if actually the solution.

**Comment by dexmar** [comment] 2021-01-26 17:10
Updated info: My son and I have both been running Fairgame and last night he got this redirect also. On my account deleting the .profile-amz folder worked, but his did not. He has a .edu Prime account. We took his laptop to my office (so basically different IP) and got the same redirect problem. Finally I reinstalled the bot on a different laptop at the office and using his .edu Prime account we tried running the bot again with the same ASIN list and he still gets the redirect. So it appears in his case anyway, Amazon has "marked" his account. His account is much newer (about a year old) and he hasn't bought nearly as many items in that time as my account which I have had for many, many years. Hopefully this helps.

**Comment by unapproachable** [comment] 2021-01-26 17:16
This is all part of a global redesign that's been affecting the folks in the EU for about a month.  It's likely just rolling out to people based on their account/IP/cookies/whatever.  It's inevitable if it gets pushed through, but I don't think end users can do much to control whether they redirect or not (as @dexmar has identified).  Deleting profiles just dumps your cookies and may get you reallocated to a different server or put in a different segment, or it may not.  It's not actually affect the code that's running, but the code you're being served.  Until we can get more developers with this use case on their machines, we'll have to work with what we have available here:

https://github.com/Hari-Nagarajan/fairgame/pull/467 

Please refrain from 'me too' posts unless you have additional information to provide.  We know about the issue, we know about some approaches to address it, and we know that everyone is a sad panda because they can't get their imminent drop item.  

If you do have an error, and it produces a stack trace that hasn't been documented, please provide as much information as you can about the page it's trying to load, what you see in the browser when it does so, and possibly save the page source if you have enough time before a crash.  Otherwise, hold tight and wait for the volunteers to get the time to update the code.

**Comment by DustWard** [comment] 2021-01-26 17:22
I am getting the same issue as everyone else. Someone asked for the adjustments I made to the files so here they are below:

For _Amazon I have `cmd /k pipenv run python app.py amazon --delay=1`

For Config I have:
`{
  "asin_groups": 3,
  "asin_list_1": ["B08L8KC1J7","B08NYP7KG6","B08P2D1JZZ","B08S6Z5285","B08NYNJ6RC","B08NYP7KG6","B08P3V572B"],
  "reserve_min_1": 400,
  "reserve_max_1": 610,
  "asin_list_2": ["B08HR5SXPS","B08HH5WF97"],
  "reserve_min_2": 650,
  "reserve_max_2": 800,
  "asin_list_3": ["B08HR9D2JS","B08HBQWBHH"],
  "reserve_min_3": 1100,
  "reserve_max_3": 1500,
  "amazon_website": "smile.amazon.com"
}
`

**Comment by mlapastora** [comment] 2021-01-26 22:04
Stupid question, but how do you checkout the dev version?

**Comment by interbiznw** [comment] 2021-01-26 23:46
> Stupid question, but how do you checkout the dev version?

Depends, did you use :

**cmd line git ?:** (use `git checkout branch origin/features/xpath-updates`

**Github desktop ?:** just use the drop-down and switch branches to origin/features/xpath-updates.

**Just downloaded the zip ?:** Just switch use this link https://github.com/Hari-Nagarajan/fairgame/tree/feature/xpath-updates and download the zip from there it will be from that dev branch.

**Comment by losnir** [comment] 2021-01-27 18:20
Same problem here, but looks like I've found a workaround. 🙂 

Turns out that the old "Offer Listing" page is still working (i.e. no redirect) if you have an old session on `amazon.com` (works with `smile.amazon.com` too), and the good news is that it seems to be decided solely on browser cookies.

_My theory is that the evaluation of the feature flag Amazon uses for the new "All Offers Display"  does not change mid-session, so that's is why old sessions works: they have that feature flag still evaluating to false (i.e. stickciness)._

What I did was to open DevTools within the old browser session, fetch the value of `document.cookie` and then execute the following JS snippet on fairgame chrome window:

```
'VALUE_OF_OLD_COOKIE'.split(';').forEach(ck => document.cookie = ck);
```
Replace `VALUE_OF_OLD_COOKIE` with the value of `docment.cookie` you retrieved of course.

Happy snatching!

**Comment by dexmar** [comment] 2021-01-28 02:56
I would love to try this sadly I fall into the camp of _deleted .profile-amz_, however I have deleted and re-ran the script a dozen times now so apparently the odds of not getting this redirect fall somewhere in the realm of winning the lottery. @losnir

**Comment by iamohd** [comment] 2021-01-28 17:34
Unfourtently it's not working for me. I am getting "ERROR: Unable to find any offers listing.  Skipping...".

**Comment by Anshul00S** [comment] 2021-01-28 19:29
same issue with me.

**Comment by baobozo** [comment] 2021-01-29 01:50
Same here, not working on amazon.com and smile.amazon.com

**Comment by deewfrank** [comment] 2021-01-29 18:35
Same here,  I am getting "ERROR: Unable to find any offers listing. Skipping...".

**Comment by cgrimm-redhat** [comment] 2021-01-29 20:45
Downloaded this PR rebult with pipenv shell and pipenv install, reran and now all is working again for me.  I am getting the redirect on in the US now.

**Comment by wxyzsupermod** [comment] 2021-01-30 03:32
I have gotten the same error after running with these commands 
pipenv run python app.py amazon --delay 3 --shipping-bypass --p (redacted) --single-shot
The Config is good as it worked before. But I am now getting
![image](https://user-images.githubusercontent.com/3249780/106346006-b48a1080-6268-11eb-8451-1a3749cca7a0.png)
I am unsure as of the cause but hoping the DEV's will get some insight from this

**Comment by DustWard** [comment] 2021-02-03 02:49
This is now completely broken for me, even using the Dev version. Is anyone getting the same thing? Looks to be trying to fetch prices, never finds them, then moves on.

**Comment by mlapastora** [comment] 2021-02-03 03:33
Not working for me either.

**Comment by cort5000** [comment] 2021-02-03 03:40
Dev Branch is working for me I was able to complete a purchase of a cheap item.

**Comment by iamohd** [comment] 2021-02-03 06:08
After trying the development branch, it worked fine.

**Closed** 2021-03-25 20:43 UTC
