### ISSUE TITLE
INFO: Failed to load prices

### ISSUE THREAD

**Issue by mh1ger** [Hari-Nagarajan/fairgame#461] opened 2021-01-06 00:24 UTC
![grafik](https://user-images.githubusercontent.com/77031464/103713929-bf30ed00-4fbd-11eb-8723-73297640a635.png)

Hi, was trying to test buy a cooking pan, login works but then i get error: Failed to load prices. Tried different ASINs, happens all the time....

Any solutions?

Regards

**Comment by DakkJaniels** [comment] 2021-01-06 01:02
domain?

**Comment by mh1ger** [comment] 2021-01-06 01:43
Sorry, forgot to mention.

smile.amazon.de

**Comment by DakkJaniels** [comment] 2021-01-06 02:12
Closing, this is a duplicate of Issue #460

**Closed by DakkJaniels** 2021-01-06 02:12 UTC
