### ISSUE TITLE
No way working under linux server

### ISSUE THREAD

**Issue by LgWagon** [Hari-Nagarajan/fairgame#419] opened 2020-12-12 08:41 UTC
I’ve tried to run the script under ubuntu 16.04, with chromedriver and —headless option, however the script hangs on ‘waiting for home page’ and ‘Lets login’. After that, it crashes with error:
‘ raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash from unknown error: cannot determine loading status from tab crashed
  (Session info: headless chrome=87.0.4280.88)
  (Driver info: chromedriver=2.41.578700, platform=Linux 4.4.0-197-generic x86_64)

Any idea? I think it would be very useful to run the script under Linux..

**Comment by DakkJaniels** [comment] 2020-12-12 14:15
Headless doesn't work

**Comment by DakkJaniels** [comment] 2020-12-12 14:16
Duplicate of #278

**Closed** 2020-12-12 14:15 UTC
